// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolygonAiBuilder.Infrastructure;

#nullable disable

namespace PolygonAiBuilder.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BuilderDbContext))]
    partial class BuilderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("PolygonAiBuilder.Domain.ApplicationSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("ApplicationSettings");
                });

            modelBuilder.Entity("PolygonAiBuilder.Domain.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtractedTextPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProblemProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderFileId")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("ProblemProjectId");

                    b.HasIndex("Sha256");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("PolygonAiBuilder.Domain.CodeArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("GeneratedFromStatementVersion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastCompileOutput")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastCompileStatus")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProblemProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProblemProjectId", "Type")
                        .IsUnique();

                    b.ToTable("CodeArtifacts");
                });

            modelBuilder.Entity("PolygonAiBuilder.Domain.CodeArtifactVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CodeArtifactId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompileStatus")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompilerOutput")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CodeArtifactId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("CodeArtifactVersions");
                });

            modelBuilder.Entity("PolygonAiBuilder.Domain.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProblemProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RollingSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProblemProjectId")
                        .IsUnique();

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("PolygonAiBuilder.Domain.ConversationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderResponseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StatementVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("StructuredActionsJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "CreatedAt");

                    b.ToTable("ConversationMessages");
                });

            modelBuilder.Entity("PolygonAiBuilder.Domain.GeneralInfo", b =>
                {
                    b.Property<Guid>("ProblemProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputFile")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("MemoryLimitMb")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputFile")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeLimitMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProblemProjectId");

                    b.ToTable("GeneralInfos", null, t =>
                        {
                            t.HasCheckConstraint("CK_GeneralInfos_DifferentFiles", "lower(InputFile) <> lower(OutputFile)");

                            t.HasCheckConstraint("CK_GeneralInfos_MemoryLimit", "MemoryLimitMb BETWEEN 4 AND 1024");

                            t.HasCheckConstraint("CK_GeneralInfos_TimeLimit", "TimeLimitMs BETWEEN 250 AND 15000 AND TimeLimitMs % 50 = 0");
                        });
                });

            modelBuilder.Entity("PolygonAiBuilder.Domain.ModelCacheEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilitiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("RefreshedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ModelId")
                        .IsUnique();

                    b.ToTable("ModelCacheEntries");
                });

            modelBuilder.Entity("PolygonAiBuilder.Domain.ProblemProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentScreen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InternalName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<long?>("NameAvailableCheckedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PolygonProblemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PolygonRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PolygonSyncPhase")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedModel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedProvider")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InternalName")
                        .IsUnique();

                    b.ToTable("ProblemProjects", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProblemProjects_CurrentScreen", "CurrentScreen BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("PolygonAiBuilder.Domain.Sample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("GeneratedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GeneratorVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("InputIsStale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("OutputIsStale")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProblemProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SolutionVersionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TestIndex")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WasManuallyEdited")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProblemProjectId", "TestIndex")
                        .IsUnique();

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("PolygonAiBuilder.Domain.Statement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCodeStale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Legend")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProblemProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProblemProjectId")
                        .IsUnique();

                    b.ToTable("Statements");
                });

            modelBuilder.Entity("PolygonAiBuilder.Domain.StatementVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Legend")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StatementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StatementId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("StatementVersions");
                });

            modelBuilder.Entity("PolygonAiBuilder.Domain.SyncOperationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProblemProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteResultSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProblemProjectId", "StartedAt");

                    b.ToTable("SyncOperationLogs");
                });

            modelBuilder.Entity("PolygonAiBuilder.Domain.TestConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Checker")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PointsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProblemProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SampleTestIndex")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ScorePerTest")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Script")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TestCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestsetName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseSampleInStatement")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProblemProjectId")
                        .IsUnique();

                    b.ToTable("TestConfigurations", null, t =>
                        {
                            t.HasCheckConstraint("CK_TestConfigurations_Score", "ScorePerTest >= 0");

                            t.HasCheckConstraint("CK_TestConfigurations_TestCount", "TestCount BETWEEN 1 AND 1000");
                        });
                });

            modelBuilder.Entity("PolygonAiBuilder.Domain.Attachment", b =>
                {
                    b.HasOne("PolygonAiBuilder.Domain.ConversationMessage", "Message")
                        .WithMany("Attachments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PolygonAiBuilder.Domain.ProblemProject", "ProblemProject")
                        .WithMany("Attachments")
                        .HasForeignKey("ProblemProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("ProblemProject");
                });

            modelBuilder.Entity("PolygonAiBuilder.Domain.CodeArtifact", b =>
                {
                    b.HasOne("PolygonAiBuilder.Domain.ProblemProject", "ProblemProject")
                        .WithMany("CodeArtifacts")
                        .HasForeignKey("ProblemProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProblemProject");
                });

            modelBuilder.Entity("PolygonAiBuilder.Domain.CodeArtifactVersion", b =>
                {
                    b.HasOne("PolygonAiBuilder.Domain.CodeArtifact", "CodeArtifact")
                        .WithMany("Versions")
                        .HasForeignKey("CodeArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodeArtifact");
                });

            modelBuilder.Entity("PolygonAiBuilder.Domain.Conversation", b =>
                {
                    b.HasOne("PolygonAiBuilder.Domain.ProblemProject", "ProblemProject")
                        .WithOne("Conversation")
                        .HasForeignKey("PolygonAiBuilder.Domain.Conversation", "ProblemProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProblemProject");
                });

            modelBuilder.Entity("PolygonAiBuilder.Domain.ConversationMessage", b =>
                {
                    b.HasOne("PolygonAiBuilder.Domain.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("PolygonAiBuilder.Domain.GeneralInfo", b =>
                {
                    b.HasOne("PolygonAiBuilder.Domain.ProblemProject", "ProblemProject")
                        .WithOne("GeneralInfo")
                        .HasForeignKey("PolygonAiBuilder.Domain.GeneralInfo", "ProblemProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProblemProject");
                });

            modelBuilder.Entity("PolygonAiBuilder.Domain.Sample", b =>
                {
                    b.HasOne("PolygonAiBuilder.Domain.ProblemProject", "ProblemProject")
                        .WithMany("Samples")
                        .HasForeignKey("ProblemProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProblemProject");
                });

            modelBuilder.Entity("PolygonAiBuilder.Domain.Statement", b =>
                {
                    b.HasOne("PolygonAiBuilder.Domain.ProblemProject", "ProblemProject")
                        .WithOne("Statement")
                        .HasForeignKey("PolygonAiBuilder.Domain.Statement", "ProblemProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProblemProject");
                });

            modelBuilder.Entity("PolygonAiBuilder.Domain.StatementVersion", b =>
                {
                    b.HasOne("PolygonAiBuilder.Domain.Statement", "Statement")
                        .WithMany("Versions")
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Statement");
                });

            modelBuilder.Entity("PolygonAiBuilder.Domain.SyncOperationLog", b =>
                {
                    b.HasOne("PolygonAiBuilder.Domain.ProblemProject", "ProblemProject")
                        .WithMany("SyncOperations")
                        .HasForeignKey("ProblemProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProblemProject");
                });

            modelBuilder.Entity("PolygonAiBuilder.Domain.TestConfiguration", b =>
                {
                    b.HasOne("PolygonAiBuilder.Domain.ProblemProject", "ProblemProject")
                        .WithOne("TestConfiguration")
                        .HasForeignKey("PolygonAiBuilder.Domain.TestConfiguration", "ProblemProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProblemProject");
                });

            modelBuilder.Entity("PolygonAiBuilder.Domain.CodeArtifact", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("PolygonAiBuilder.Domain.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("PolygonAiBuilder.Domain.ConversationMessage", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("PolygonAiBuilder.Domain.ProblemProject", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("CodeArtifacts");

                    b.Navigation("Conversation")
                        .IsRequired();

                    b.Navigation("GeneralInfo")
                        .IsRequired();

                    b.Navigation("Samples");

                    b.Navigation("Statement")
                        .IsRequired();

                    b.Navigation("SyncOperations");

                    b.Navigation("TestConfiguration")
                        .IsRequired();
                });

            modelBuilder.Entity("PolygonAiBuilder.Domain.Statement", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
